source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'mysql2'
gem 'devise'
gem 'will_paginate'
gem 'resque'
gem 'mini_magick'
gem 'capistrano'
gem 'activemerchant'
gem 'jquery-rails'
gem 'SystemTimer'